; generated by PrusaSlicer 2.9.4 on 2026-02-09 at 07:22:51 UTC

; 

; external perimeters extrusion width = 2.00mm
; perimeters extrusion width = 2.00mm
; infill extrusion width = 2.00mm
; solid infill extrusion width = 2.00mm
; top infill extrusion width = 2.00mm
; first layer extrusion width = 2.00mm

M104 S250 T1 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S250 T1 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
T1
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:1
;HEIGHT:0.5
G1 E627.2942 F2400
G92 E0
G1 Z1 F600
G1 X295.215 Y295.215
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:2
G1 F600
G1 X204.785 Y295.215 E15.41481
G1 X204.785 Y204.785 E28.82962
G1 X295.215 Y204.785 E42.24443
G1 X295.215 Y294.915 E55.61474
G1 E53.61474 F2400
G92 E0
G1 X297.107 Y297.107 F600
G1 E2 F2400
G1 F600
G1 X202.893 Y297.107 E15.97615
G1 X202.893 Y202.893 E29.9523
G1 X297.107 Y202.893 E43.92845
G1 X297.107 Y296.807 E57.86009
G1 E55.86009 F2400
G92 E0
G1 X299 Y299 F600
G1 E2 F2400
;TYPE:External perimeter
G1 F600
G1 X201 Y299 E16.53778
G1 X201 Y201 E31.07556
G1 X299 Y201 E45.61334
G1 X299 Y298.7 E60.10661
G1 X297.022 Y298.997
G1 E58.10661 F2400
G92 E0
G1 X206.719 Y206.358 F600
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:2.45924
G1 F600
G1 X206.511 Y206.151 E2.05409
G1 X206.227 Y206.227 E2.10828
G1 X206.151 Y206.511 E2.16247
G1 X206.358 Y206.719 E2.21656
G1 X206.642 Y206.642 E2.2708
;WIDTH:2
G1 X206.205 Y209.666 E2.72405
G1 X209.666 Y206.205 E3.45014
G1 X212.342 Y206.205 E3.84711
G1 X206.205 Y212.342 E5.1346
G1 X206.205 Y215.019 E5.53172
G1 X215.019 Y206.205 E7.38082
G1 X217.696 Y206.205 E7.77794
G1 X206.205 Y217.696 E10.18865
G1 X206.205 Y220.372 E10.58562
G1 X220.372 Y206.205 E13.55773
G1 X223.049 Y206.205 E13.95485
G1 X206.205 Y223.049 E17.48857
G1 X206.205 Y225.726 E17.88569
G1 X225.726 Y206.205 E21.98102
G1 X228.402 Y206.205 E22.37799
G1 X206.205 Y228.402 E27.03472
G1 X206.205 Y231.079 E27.43184
G1 X231.079 Y206.205 E32.65018
G1 X233.756 Y206.205 E33.0473
G1 X206.205 Y233.756 E38.82725
G1 X206.205 Y236.432 E39.22422
G1 X236.432 Y206.205 E45.56557
G1 X239.109 Y206.205 E45.96269
G1 X206.205 Y239.109 E52.86565
G1 X206.205 Y241.786 E53.26277
G1 X241.786 Y206.205 E60.72735
G1 X244.462 Y206.205 E61.12432
G1 X206.205 Y244.462 E69.1503
G1 X206.205 Y247.139 E69.54742
G1 X247.139 Y206.205 E78.13501
G1 X249.816 Y206.205 E78.53213
G1 X206.205 Y249.816 E87.68133
G1 X206.205 Y252.492 E88.0783
G1 X252.492 Y206.205 E97.7889
G1 X255.169 Y206.205 E98.18602
G1 X206.205 Y255.169 E108.45823
G1 X206.205 Y257.846 E108.85535
G1 X257.846 Y206.205 E119.68917
G1 X260.523 Y206.205 E120.08629
G1 X206.205 Y260.523 E131.48172
G1 X206.205 Y263.199 E131.87869
G1 X263.199 Y206.205 E143.83552
G1 X265.876 Y206.205 E144.23264
G1 X206.205 Y265.876 E156.75108
G1 X206.205 Y268.553 E157.1482
G1 X268.553 Y206.205 E170.22825
G1 X271.229 Y206.205 E170.62522
G1 X206.205 Y271.229 E184.26667
G1 X206.205 Y273.906 E184.66379
G1 X273.906 Y206.205 E198.86685
G1 X276.583 Y206.205 E199.26397
G1 X206.205 Y276.583 E214.02864
G1 X206.205 Y279.259 E214.42561
G1 X279.259 Y206.205 E229.75169
G1 X281.936 Y206.205 E230.14881
G1 X206.205 Y281.936 E246.0365
G1 X206.205 Y284.613 E246.43362
G1 X284.613 Y206.205 E262.88292
G1 X287.289 Y206.205 E263.27989
G1 X206.205 Y287.289 E280.29059
G1 X206.205 Y289.966 E280.68771
G1 X289.966 Y206.205 E298.26002
G1 E296.26002 F2400
G92 E0
G1 X294.402 Y205.748 F600
G1 E2 F2400
;WIDTH:1.8073
G1 F600
G1 X294.252 Y205.598 E2.02826
G1 X294.047 Y205.653 E2.05654
G1 X293.992 Y205.858 E2.08482
G1 X294.142 Y206.008 E2.11308
G1 X294.347 Y205.953 E2.14136
;WIDTH:1.85548
G1 X293.921 Y206.016 E2.20036
;WIDTH:1.90365
G1 X293.495 Y206.079 E2.26099
;WIDTH:1.95183
G1 X293.069 Y206.142 E2.32325
;WIDTH:2
G1 X292.643 Y206.205 E2.38713
G1 X206.205 Y292.643 E20.52105
G1 X206.142 Y293.069 E20.58493
;WIDTH:1.95183
G1 X206.079 Y293.495 E20.64719
;WIDTH:1.90365
G1 X206.016 Y293.921 E20.70782
;WIDTH:1.85548
G1 X205.953 Y294.347 E20.76682
;WIDTH:1.8073
G1 X205.748 Y294.402 E20.7951
G1 X205.598 Y294.252 E20.82336
G1 X205.653 Y294.047 E20.85164
G1 X205.858 Y293.992 E20.87992
G1 X206.008 Y294.142 E20.90818
;WIDTH:2
G1 X207.729 Y293.795 E21.16862
G1 X293.795 Y207.729 E39.2245
G1 X293.795 Y210.406 E39.62162
G1 X210.406 Y293.795 E57.11589
G1 X213.083 Y293.795 E57.51301
G1 X293.795 Y213.083 E74.44567
G1 X293.795 Y215.759 E74.84264
G1 X215.759 Y293.795 E91.21389
G1 X218.436 Y293.795 E91.61101
G1 X293.795 Y218.436 E107.42065
G1 X293.795 Y221.113 E107.81777
G1 X221.113 Y293.795 E123.0658
G1 X223.789 Y293.795 E123.46277
G1 X293.795 Y223.789 E138.1494
G1 X293.795 Y226.466 E138.54652
G1 X226.466 Y293.795 E152.67154
G1 X229.143 Y293.795 E153.06866
G1 X293.795 Y229.143 E166.63207
G1 X293.795 Y231.819 E167.02904
G1 X231.819 Y293.795 E180.03105
G1 X234.496 Y293.795 E180.42817
G1 X293.795 Y234.496 E192.86857
G1 X293.795 Y237.173 E193.26569
G1 X237.173 Y293.795 E205.14448
G1 X239.849 Y293.795 E205.54145
G1 X293.795 Y239.849 E216.85884
G1 X293.795 Y242.526 E217.25596
G1 X242.526 Y293.795 E228.01174
G1 X245.203 Y293.795 E228.40886
G1 X293.795 Y245.203 E238.60303
G1 X293.795 Y247.879 E239
G1 X247.879 Y293.795 E248.63277
G1 X250.556 Y293.795 E249.02989
G1 X293.795 Y250.556 E258.10105
G1 X293.795 Y253.233 E258.49817
G1 X253.233 Y293.795 E267.00771
G1 X255.909 Y293.795 E267.40468
G1 X293.795 Y255.909 E275.35282
G1 X293.795 Y258.586 E275.74994
G1 X258.586 Y293.795 E283.13647
G1 X261.263 Y293.795 E283.53359
G1 X293.795 Y261.263 E290.35851
G1 X293.795 Y263.94 E290.75563
G1 X263.939 Y293.795 E297.01905
G1 X266.616 Y293.795 E297.41617
G1 X293.795 Y266.616 E303.11808
G1 X293.795 Y269.293 E303.5152
G1 X269.293 Y293.795 E308.6555
G1 X271.97 Y293.795 E309.05262
G1 X293.795 Y271.97 E313.63131
G1 X293.795 Y274.646 E314.02828
G1 X274.646 Y293.795 E318.04557
G1 X277.323 Y293.795 E318.44269
G1 X293.795 Y277.323 E321.89837
G1 X293.795 Y280 E322.29549
G1 X280 Y293.795 E325.18956
G1 X282.676 Y293.795 E325.58653
G1 X293.795 Y282.676 E327.9192
G1 X293.795 Y285.353 E328.31632
G1 X285.353 Y293.795 E330.08738
G1 X288.03 Y293.795 E330.4845
G1 X293.795 Y288.03 E331.69395
G1 X294.808 Y289.925 E332.01271
;WIDTH:1.8073
G1 X294.658 Y289.774 E332.04107
G1 X294.453 Y289.829 E332.06935
G1 X294.398 Y290.035 E332.09776
G1 X294.548 Y290.185 E332.12602
G1 X294.753 Y290.13 E332.1543
;WIDTH:1.85548
G1 X294.514 Y290.274 E332.19253
;WIDTH:1.90365
G1 X294.274 Y290.418 E332.23194
;WIDTH:1.95183
G1 X294.035 Y290.562 E332.27228
;WIDTH:2
G1 X293.795 Y290.706 E332.3138
G1 X290.706 Y293.795 E332.96184
G1 X290.562 Y294.035 E333.00336
;WIDTH:1.95183
G1 X290.418 Y294.274 E333.0437
;WIDTH:1.90365
G1 X290.274 Y294.514 E333.08311
;WIDTH:1.85548
G1 X290.13 Y294.753 E333.12134
;WIDTH:1.8073
G1 X289.925 Y294.808 E333.14962
G1 X289.774 Y294.658 E333.17798
G1 X289.829 Y294.453 E333.20626
G1 X290.035 Y294.398 E333.23467
G1 X290.185 Y294.548 E333.26293
;WIDTH:2
G1 X293.863 Y293.863 E333.81792
;WIDTH:2.24139
G1 X293.605 Y293.932 E333.86259
G1 X293.417 Y293.743 E333.90718
G1 X293.486 Y293.486 E333.95169
G1 X293.743 Y293.417 E333.9962
G1 X293.932 Y293.605 E334.04079
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; objects_info = {"objects":[]}
; filament used [mm] = 0.00, 10481.20
; filament used [cm3] = 0.00, 66.86
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 1h 50m 16s
; estimated printing time (silent mode) = 1h 50m 17s
; estimated first layer printing time (normal mode) = 10m 27s
; estimated first layer printing time (silent mode) = 10m 27s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,500x0,500x500,0x500
; bed_temperature = 0,0
; bed_temperature_extruder = 0
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 1
; bridge_speed = 10
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0,0
; chamber_temperature = 0,0
; color_change_gcode = M600
; colorprint_heights = 
; complete_objects = 0
; cooling = 1,1
; cooling_perimeter_transition_distance = 0,0
; cooling_slowdown_logic = uniform_cooling,uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ;
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 3,3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0,0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 2
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #000000;#F0F0F0
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 1,1
; extrusion_width = 2
; fan_always_on = 0,0
; fan_below_layer_time = 60,60
; filament_abrasive = 0,0
; filament_colour = #29B2B2;#29B2B2
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 0,0
; filament_density = 0,0
; filament_deretract_speed = nil,nil
; filament_diameter = 2.85,2.85
; filament_infill_max_crossing_speed = 0,0
; filament_infill_max_speed = 0,0
; filament_load_time = 0,0
; filament_loading_speed = 10,10
; filament_loading_speed_start = 10,10
; filament_max_volumetric_speed = 0,0
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_multitool_ramming = 0,0
; filament_multitool_ramming_flow = 10,10
; filament_multitool_ramming_volume = 10,10
; filament_notes = ;
; filament_purge_multiplier = 100%,100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil,nil
; filament_retract_before_wipe = nil,nil
; filament_retract_layer_change = nil,nil
; filament_retract_length = nil,nil
; filament_retract_length_toolchange = nil,nil
; filament_retract_lift = nil,nil
; filament_retract_lift_above = nil,nil
; filament_retract_lift_below = nil,nil
; filament_retract_restart_extra = nil,nil
; filament_retract_restart_extra_toolchange = nil,nil
; filament_retract_speed = nil,nil
; filament_seam_gap_distance = nil,nil
; filament_settings_id = ABS-2.85MM;ABS-2.85MM
; filament_shrinkage_compensation_xy = 0%,0%
; filament_shrinkage_compensation_z = 0%,0%
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_stamping_distance = 0,0
; filament_stamping_loading_speed = 20,20
; filament_toolchange_delay = 0,0
; filament_travel_lift_before_obstacle = nil,nil
; filament_travel_max_lift = nil,nil
; filament_travel_ramping_lift = nil,nil
; filament_travel_slope = nil,nil
; filament_type = ABS;ABS
; filament_unload_time = 0,0
; filament_unloading_speed = 10,10
; filament_unloading_speed_start = 10,10
; filament_vendor = (Unknown)
; filament_wipe = nil,nil
; fill_angle = 45
; fill_density = 20%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0,0
; first_layer_extrusion_width = 2
; first_layer_height = 0.5
; first_layer_infill_speed = 0
; first_layer_speed = 10
; first_layer_speed_over_raft = 10
; first_layer_temperature = 250,250
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 10
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil,nil
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 2
; infill_extrusion_width = 2
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 10
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 10
; ironing_type = top
; layer_gcode = 
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 0,0
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 200
; max_print_speed = 10
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35,35
; min_feature_size = 25%
; min_layer_height = 0.07,0.07
; min_print_speed = 10,10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 2,2
; nozzle_high_flow = 0,0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0,0
; overhang_fan_speed_1 = 0,0
; overhang_fan_speed_2 = 0,0
; overhang_fan_speed_3 = 0,0
; overhang_speed_0 = 10
; overhang_speed_1 = 10
; overhang_speed_2 = 10
; overhang_speed_3 = 10
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 2
; perimeter_extrusion_width = 2
; perimeter_generator = arachne
; perimeter_speed = 10
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = KUKA_3D_PRINTER
; printer_model = 
; printer_notes = 
; printer_settings_id = KUKA
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 0%,0%
; retract_layer_change = 0,0
; retract_length = 2,2
; retract_length_toolchange = 10,10
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 0,0
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5,5
; small_perimeter_speed = 10
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 2
; solid_infill_extrusion_width = 2
; solid_infill_speed = 10
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n";"; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 2
; support_material_extrusion_width = 2
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 2
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 10
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 10
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 250,250
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 2
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 10
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0,0
; travel_max_lift = 0,0
; travel_ramping_lift = 0,0
; travel_short_distance_acceleration = 0
; travel_slope = 0,0
; travel_speed = 10
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 3
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0,140,140,0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
