from __future__ import annotations

from decimal import Decimal, InvalidOperation
from typing import Iterable, Sequence


RESIN_TOOL_ID = 2
RESIN_GCODE_TOOL = 1
DEFAULT_LINE_WIDTH_MM = 2.0
EXTRUSION_PER_MM3 = 0.14834
TEST_MATRIX_MAX_LINES = 45
TEST_MATRIX_RANGE_STEP = Decimal("0.1")


def expand_test_values(text: str, *, label: str = "参数") -> list[float]:
    raw = str(text).strip()
    if not raw:
        raise ValueError(f"{label}不能为空。")
    parts = [part.strip() for part in raw.split("-")]
    if len(parts) == 1:
        try:
            value = Decimal(parts[0])
        except InvalidOperation as exc:
            raise ValueError(f"{label}格式无效。") from exc
        if value <= 0:
            raise ValueError(f"{label}必须大于 0。")
        return [float(value)]
    if len(parts) != 2 or not parts[0] or not parts[1]:
        raise ValueError(f"{label}范围格式应为 0.5-1.0。")
    try:
        start = Decimal(parts[0])
        end = Decimal(parts[1])
    except InvalidOperation as exc:
        raise ValueError(f"{label}范围格式无效。") from exc
    if start <= 0 or end <= 0:
        raise ValueError(f"{label}必须大于 0。")
    if end < start:
        raise ValueError(f"{label}范围终点不能小于起点。")

    values = []
    current = start
    while current <= end + Decimal("0.000000001"):
        values.append(float(current.quantize(Decimal("0.1"))))
        current += TEST_MATRIX_RANGE_STEP
    return values


def _validate_positive_sequence(values: Sequence[float], label: str) -> list[float]:
    result = [float(v) for v in values]
    if not result:
        raise ValueError(f"{label}不能为空。")
    if any(v <= 0.0 for v in result):
        raise ValueError(f"{label}必须全部大于 0。")
    return result


def _pose_values(
    start_pose: Sequence[float],
) -> tuple[float, float, float, float, float, float]:
    if len(start_pose) != 6:
        raise ValueError("start_pose must contain X/Y/Z/A/B/C")
    return tuple(float(v) for v in start_pose)  # type: ignore[return-value]


def _header(start_pose: Sequence[float]) -> list[str]:
    x, y, z, a, b, c = _pose_values(start_pose)
    return [
        "; generated by gcode_planner.print_test_generator",
        "G21",
        "G90",
        "M82",
        f"T{RESIN_GCODE_TOOL}",
        f"G92 X{x:.6f} Y{y:.6f} Z{z:.6f} A{a:.6f} B{b:.6f} C{c:.6f} E0",
        ";TYPE:PrintTest",
        f";WIDTH:{DEFAULT_LINE_WIDTH_MM:.3f}",
    ]


def _feed(speed_mm_s: float) -> float:
    speed = float(speed_mm_s)
    if speed <= 0.0:
        raise ValueError("speed_mm_s must be > 0")
    return speed * 60.0


def generate_z_adjust_gcode(
    *,
    start_pose: Sequence[float],
    target_z: float,
    speed_mm_s: float,
) -> list[str]:
    x, y, _z, a, b, c = _pose_values(start_pose)
    feed = _feed(speed_mm_s)
    lines = _header(start_pose)
    lines.append(
        f"G1 X{x:.6f} Y{y:.6f} Z{float(target_z):.6f} "
        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
    )
    return lines


def generate_test_line_gcode(
    *,
    start_pose: Sequence[float],
    layer_height_mm: float,
    speed_mm_s: float,
    line_length_mm: float = 200.0,
    finish_lift_mm: float = 10.0,
) -> list[str]:
    x, y, z, a, b, c = _pose_values(start_pose)
    layer_height = float(layer_height_mm)
    line_length = float(line_length_mm)
    finish_lift = float(finish_lift_mm)
    if layer_height <= 0.0:
        raise ValueError("layer_height_mm must be > 0")
    if line_length <= 0.0:
        raise ValueError("line_length_mm must be > 0")
    if finish_lift < 0.0:
        raise ValueError("finish_lift_mm must be >= 0")

    feed = _feed(speed_mm_s)
    total_e = line_length * DEFAULT_LINE_WIDTH_MM * layer_height * EXTRUSION_PER_MM3
    end_x = x + line_length
    lift_z = z + finish_lift
    lines = _header(start_pose)
    lines.append(f";HEIGHT:{layer_height:.6f}")
    lines.append(
        f"G1 X{end_x:.6f} Y{y:.6f} Z{z:.6f} A{a:.6f} B{b:.6f} C{c:.6f} "
        f"E{total_e:.6f} F{feed:.3f}"
    )
    if finish_lift > 0.0:
        lines.append(
            f"G1 X{end_x:.6f} Y{y:.6f} Z{lift_z:.6f} "
            f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
        )
    return lines


def generate_test_matrix_gcode(
    *,
    start_pose: Sequence[float],
    layer_heights_mm: Sequence[float],
    extrusion_scales: Sequence[float],
    speed_mm_s: float,
    line_length_mm: float = 300.0,
    y_spacing_mm: float = 10.0,
    finish_lift_mm: float = 10.0,
    max_lines: int = TEST_MATRIX_MAX_LINES,
) -> list[str]:
    x, y, base_z, a, b, c = _pose_values(start_pose)
    layer_heights = _validate_positive_sequence(layer_heights_mm, "层高")
    scales = _validate_positive_sequence(extrusion_scales, "挤出倍率")
    line_count = len(layer_heights) * len(scales)
    if line_count > int(max_lines):
        raise ValueError(
            f"测试矩阵最多允许 {int(max_lines)} 条线，当前为 {line_count} 条。"
        )

    line_length = float(line_length_mm)
    y_spacing = float(y_spacing_mm)
    finish_lift = float(finish_lift_mm)
    if line_length <= 0.0:
        raise ValueError("line_length_mm must be > 0")
    if y_spacing <= 0.0:
        raise ValueError("y_spacing_mm must be > 0")
    if finish_lift < 0.0:
        raise ValueError("finish_lift_mm must be >= 0")

    feed = _feed(speed_mm_s)
    lines = _header(start_pose)
    end_x = x + line_length
    current_e = 0.0
    index = 0
    previous_lift_z = None

    for layer_height in layer_heights:
        for scale in scales:
            line_y = y + index * y_spacing
            print_z = base_z + layer_height
            lift_z = print_z + finish_lift
            delta_e = (
                line_length
                * DEFAULT_LINE_WIDTH_MM
                * layer_height
                * EXTRUSION_PER_MM3
                * scale
            )
            current_e += delta_e

            lines.append(f";TEST_LINE:{index + 1}")
            lines.append(f";HEIGHT:{layer_height:.6f}")
            lines.append(f";EXTRUDE_SCALE:{scale:.6f}")
            if previous_lift_z is None:
                lines.append(
                    f"G0 X{x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                )
            else:
                lines.append(
                    f"G0 X{x:.6f} Y{line_y:.6f} Z{previous_lift_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                )
                lines.append(
                    f"G0 X{x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                )
            lines.append(
                f"G1 X{end_x:.6f} Y{line_y:.6f} Z{print_z:.6f} A{a:.6f} B{b:.6f} C{c:.6f} "
                f"E{current_e:.6f} F{feed:.3f}"
            )
            if finish_lift > 0.0:
                lines.append(
                    f"G0 X{end_x:.6f} Y{line_y:.6f} Z{lift_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                )
                previous_lift_z = lift_z
            else:
                previous_lift_z = print_z
            index += 1
    return lines


def format_gcode(lines: Iterable[str]) -> str:
    return "\n".join(lines) + "\n"
