from __future__ import annotations

from decimal import Decimal, InvalidOperation
from typing import Iterable, Sequence

from path_processing_core.head_calibration import HeadCalibration


FIBER_TOOL_ID = 1
FIBER_GCODE_TOOL = 0
RESIN_TOOL_ID = 2
RESIN_GCODE_TOOL = 1
DEFAULT_LINE_WIDTH_MM = 2.0
EXTRUSION_PER_MM3 = 1.0 / (3.141592653589793 * (1.75 / 2.0) ** 2)
TEST_MATRIX_MAX_LINES = 45
TEST_MATRIX_RANGE_STEP = Decimal("0.1")


def expand_test_values(text: str, *, label: str = "参数") -> list[float]:
    raw = str(text).strip()
    if not raw:
        raise ValueError(f"{label}不能为空。")
    parts = [part.strip() for part in raw.split("-")]
    if len(parts) == 1:
        try:
            value = Decimal(parts[0])
        except InvalidOperation as exc:
            raise ValueError(f"{label}格式无效。") from exc
        if value <= 0:
            raise ValueError(f"{label}必须大于 0。")
        return [float(value)]
    if len(parts) != 2 or not parts[0] or not parts[1]:
        raise ValueError(f"{label}范围格式应为 0.5-1.0。")
    try:
        start = Decimal(parts[0])
        end = Decimal(parts[1])
    except InvalidOperation as exc:
        raise ValueError(f"{label}范围格式无效。") from exc
    if start <= 0 or end <= 0:
        raise ValueError(f"{label}必须大于 0。")
    if end < start:
        raise ValueError(f"{label}范围终点不能小于起点。")

    values = []
    current = start
    while current <= end + Decimal("0.000000001"):
        values.append(float(current))
        current += TEST_MATRIX_RANGE_STEP
    return values


def _validate_positive_sequence(values: Sequence[float], label: str) -> list[float]:
    result = [float(v) for v in values]
    if not result:
        raise ValueError(f"{label}不能为空。")
    if any(v <= 0.0 for v in result):
        raise ValueError(f"{label}必须全部大于 0。")
    return result


def _pose_values(
    start_pose: Sequence[float],
) -> tuple[float, float, float, float, float, float]:
    if len(start_pose) != 6:
        raise ValueError("start_pose must contain X/Y/Z/A/B/C")
    return tuple(float(v) for v in start_pose)  # type: ignore[return-value]


def _header(start_pose: Sequence[float], *, reset_e: bool = True) -> list[str]:
    x, y, z, a, b, c = _pose_values(start_pose)
    pose_line = f"G92 X{x:.6f} Y{y:.6f} Z{z:.6f} A{a:.6f} B{b:.6f} C{c:.6f}"
    if reset_e:
        pose_line += " E0"
    return [
        "; generated by gcode_planner.print_test_generator",
        "G21",
        "G90",
        "M82",
        pose_line,
        ";TYPE:PrintTest",
        f";WIDTH:{DEFAULT_LINE_WIDTH_MM:.3f}",
    ]


def _feed(speed_mm_s: float) -> float:
    speed = float(speed_mm_s)
    if speed <= 0.0:
        raise ValueError("speed_mm_s must be > 0")
    return speed * 60.0


def generate_z_adjust_gcode(
    *,
    start_pose: Sequence[float],
    target_z: float,
    speed_mm_s: float,
) -> list[str]:
    x, y, _z, a, b, c = _pose_values(start_pose)
    feed = _feed(speed_mm_s)
    lines = _header(start_pose, reset_e=False)
    lines.append(
        f"G1 X{x:.6f} Y{y:.6f} Z{float(target_z):.6f} "
        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
    )
    return lines


def generate_pose_adjust_gcode(
    *,
    start_pose: Sequence[float],
    target_pose: Sequence[float],
    speed_mm_s: float,
) -> list[str]:
    _pose_values(start_pose)
    x, y, z, a, b, c = _pose_values(target_pose)
    feed = _feed(speed_mm_s)
    lines = _header(start_pose, reset_e=False)
    lines.append(
        f"G1 X{x:.6f} Y{y:.6f} Z{z:.6f} "
        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
    )
    return lines


def generate_test_line_gcode(
    *,
    start_pose: Sequence[float],
    layer_height_mm: float,
    speed_mm_s: float,
    line_length_mm: float = 200.0,
    finish_lift_mm: float = 10.0,
    prime_length_mm: float = 0.0,
    retract_length_mm: float = 0.0,
    prime_speed_mm_s: float = 2.0,
    retract_speed_mm_s: float = 8.0,
) -> list[str]:
    x, y, z, a, b, c = _pose_values(start_pose)
    layer_height = float(layer_height_mm)
    line_length = float(line_length_mm)
    finish_lift = float(finish_lift_mm)
    prime_length = float(prime_length_mm)
    retract_length = float(retract_length_mm)
    if layer_height <= 0.0:
        raise ValueError("layer_height_mm must be > 0")
    if line_length <= 0.0:
        raise ValueError("line_length_mm must be > 0")
    if finish_lift < 0.0:
        raise ValueError("finish_lift_mm must be >= 0")
    if prime_length < 0.0:
        raise ValueError("prime_length_mm must be >= 0")
    if retract_length < 0.0:
        raise ValueError("retract_length_mm must be >= 0")

    feed = _feed(speed_mm_s)
    prime_feed = _feed(prime_speed_mm_s)
    retract_feed = _feed(retract_speed_mm_s)
    e_per_path_mm = DEFAULT_LINE_WIDTH_MM * layer_height * EXTRUSION_PER_MM3
    prime_e = prime_length
    retract_e = retract_length
    total_e = line_length * e_per_path_mm
    end_x = x + line_length
    lift_z = z + finish_lift
    lines = _header(start_pose)
    current_e = 0.0
    lines.append(f";HEIGHT:{layer_height:.6f}")
    lines.append(f";PRIME_FILAMENT_LENGTH:{prime_length:.6f}")
    lines.append(f";RETRACT_FILAMENT_LENGTH:{retract_length:.6f}")
    if prime_e > 0.0:
        current_e += prime_e
        lines.append(
            f"G1 X{x:.6f} Y{y:.6f} Z{z:.6f} A{a:.6f} B{b:.6f} C{c:.6f} "
            f"E{current_e:.6f} F{prime_feed:.3f}"
        )
    current_e += total_e
    lines.append(
        f"G1 X{end_x:.6f} Y{y:.6f} Z{z:.6f} A{a:.6f} B{b:.6f} C{c:.6f} "
        f"E{current_e:.6f} F{feed:.3f}"
    )
    if retract_e > 0.0:
        current_e -= retract_e
        lines.append(
            f"G1 X{end_x:.6f} Y{y:.6f} Z{z:.6f} A{a:.6f} B{b:.6f} C{c:.6f} "
            f"E{current_e:.6f} F{retract_feed:.3f}"
        )
    if finish_lift > 0.0:
        lines.append(
            f"G1 X{end_x:.6f} Y{y:.6f} Z{lift_z:.6f} "
            f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
        )
    return lines


def generate_test_matrix_gcode(
    *,
    start_pose: Sequence[float],
    layer_heights_mm: Sequence[float],
    extrusion_scales: Sequence[float],
    speed_mm_s: float,
    line_length_mm: float = 300.0,
    y_spacing_mm: float = 10.0,
    finish_lift_mm: float = 10.0,
    max_lines: int = TEST_MATRIX_MAX_LINES,
    prime_length_mm: float = 0.0,
    retract_length_mm: float = 0.0,
    prime_speed_mm_s: float = 2.0,
    retract_speed_mm_s: float = 8.0,
    lift_between_lines: bool = True,
    extrude_by_path_length: bool = False,
) -> list[str]:
    x, y, base_z, a, b, c = _pose_values(start_pose)
    layer_heights = _validate_positive_sequence(layer_heights_mm, "层高")
    scales = _validate_positive_sequence(extrusion_scales, "挤出倍率")
    line_count = len(layer_heights) * len(scales)
    if line_count > int(max_lines):
        raise ValueError(
            f"测试矩阵最多允许 {int(max_lines)} 条线，当前为 {line_count} 条。"
        )

    line_length = float(line_length_mm)
    y_spacing = float(y_spacing_mm)
    finish_lift = float(finish_lift_mm)
    prime_length = float(prime_length_mm)
    retract_length = float(retract_length_mm)
    if line_length <= 0.0:
        raise ValueError("line_length_mm must be > 0")
    if y_spacing <= 0.0:
        raise ValueError("y_spacing_mm must be > 0")
    if finish_lift < 0.0:
        raise ValueError("finish_lift_mm must be >= 0")
    if prime_length < 0.0:
        raise ValueError("prime_length_mm must be >= 0")
    if retract_length < 0.0:
        raise ValueError("retract_length_mm must be >= 0")

    feed = _feed(speed_mm_s)
    prime_feed = _feed(prime_speed_mm_s)
    retract_feed = _feed(retract_speed_mm_s)
    lines = _header(start_pose)
    end_x = x + line_length
    current_e = 0.0
    index = 0
    previous_lift_z = None
    current_x, current_y, current_z = x, y, base_z

    for layer_height in layer_heights:
        for scale in scales:
            line_y = y + index * y_spacing
            print_z = base_z + layer_height
            lift_z = print_z + finish_lift
            line_start_x = x if index % 2 == 0 else end_x
            line_end_x = end_x if index % 2 == 0 else x
            if extrude_by_path_length:
                e_per_path_mm = scale
            else:
                e_per_path_mm = (
                    DEFAULT_LINE_WIDTH_MM * layer_height * EXTRUSION_PER_MM3 * scale
                )
            prime_e = prime_length
            retract_e = retract_length
            delta_e = line_length * e_per_path_mm

            lines.append(f";TEST_LINE:{index + 1}")
            lines.append(f";HEIGHT:{layer_height:.6f}")
            lines.append(f";EXTRUDE_SCALE:{scale:.6f}")
            lines.append(f";PRIME_FILAMENT_LENGTH:{prime_length:.6f}")
            lines.append(f";RETRACT_FILAMENT_LENGTH:{retract_length:.6f}")
            if lift_between_lines:
                if previous_lift_z is None:
                    lines.append(
                        f"G0 X{line_start_x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                    )
                else:
                    lines.append(
                        f"G0 X{line_start_x:.6f} Y{line_y:.6f} Z{previous_lift_z:.6f} "
                        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                    )
                    lines.append(
                        f"G0 X{line_start_x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                    )
            elif (
                current_x != line_start_x
                or current_y != line_y
                or current_z != print_z
            ):
                lines.append(
                    f"G0 X{line_start_x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                )
                current_x, current_y, current_z = line_start_x, line_y, print_z
            if extrude_by_path_length and retract_e > 0.0:
                current_e -= retract_e
                lines.append(
                    f"G1 X{line_start_x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} "
                    f"E{current_e:.6f} F{retract_feed:.3f}"
                )
            if prime_e > 0.0:
                current_e += prime_e
                lines.append(
                    f"G1 X{line_start_x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} "
                    f"E{current_e:.6f} F{prime_feed:.3f}"
                )
            current_e += delta_e
            lines.append(
                f"G1 X{line_end_x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                f"A{a:.6f} B{b:.6f} C{c:.6f} "
                f"E{current_e:.6f} F{feed:.3f}"
            )
            current_x, current_y, current_z = line_end_x, line_y, print_z
            if retract_e > 0.0 and not extrude_by_path_length:
                current_e -= retract_e
                lines.append(
                    f"G1 X{line_end_x:.6f} Y{line_y:.6f} Z{print_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} "
                    f"E{current_e:.6f} F{retract_feed:.3f}"
                )
            if lift_between_lines:
                if finish_lift > 0.0:
                    lines.append(
                        f"G0 X{line_end_x:.6f} Y{line_y:.6f} Z{lift_z:.6f} "
                        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                    )
                    previous_lift_z = lift_z
                else:
                    previous_lift_z = print_z
            else:
                next_y = line_y + y_spacing
                lines.append(
                    f"G0 X{line_end_x:.6f} Y{next_y:.6f} Z{print_z:.6f} "
                    f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
                )
                current_x, current_y, current_z = line_end_x, next_y, print_z
            index += 1

    if not lift_between_lines and finish_lift > 0.0:
        lines.append(
            f"G0 X{current_x:.6f} Y{current_y:.6f} Z{current_z + finish_lift:.6f} "
            f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
        )
    return lines


def _gcode_tool_for_head(tool: str) -> int:
    normalized = str(tool).strip().lower()
    if normalized == "fiber":
        return FIBER_GCODE_TOOL
    if normalized == "resin":
        return RESIN_GCODE_TOOL
    raise ValueError("tool must be 'fiber' or 'resin'")


def _insert_tool_selection(lines: Sequence[str], *, gcode_tool: int) -> list[str]:
    result = list(lines)
    try:
        insert_at = result.index("M82") + 1
    except ValueError:
        insert_at = 0
    result.insert(insert_at, f"T{int(gcode_tool)}")
    return result


def generate_head_test_matrix_gcode(
    *,
    start_pose: Sequence[float],
    tool: str,
    layer_heights_mm: Sequence[float],
    extrusion_scales: Sequence[float],
    speed_mm_s: float,
    line_length_mm: float = 300.0,
    y_spacing_mm: float = 10.0,
    finish_lift_mm: float = 10.0,
    max_lines: int = TEST_MATRIX_MAX_LINES,
    prime_length_mm: float = 0.0,
    retract_length_mm: float = 0.0,
    prime_speed_mm_s: float = 2.0,
    retract_speed_mm_s: float = 8.0,
) -> list[str]:
    gcode_tool = _gcode_tool_for_head(tool)
    lines = generate_test_matrix_gcode(
        start_pose=start_pose,
        layer_heights_mm=layer_heights_mm,
        extrusion_scales=extrusion_scales,
        speed_mm_s=speed_mm_s,
        line_length_mm=line_length_mm,
        y_spacing_mm=y_spacing_mm,
        finish_lift_mm=finish_lift_mm,
        max_lines=max_lines,
        prime_length_mm=prime_length_mm,
        retract_length_mm=retract_length_mm,
        prime_speed_mm_s=prime_speed_mm_s,
        retract_speed_mm_s=retract_speed_mm_s,
        lift_between_lines=gcode_tool != RESIN_GCODE_TOOL,
        extrude_by_path_length=gcode_tool == FIBER_GCODE_TOOL,
    )
    return _insert_tool_selection(lines, gcode_tool=gcode_tool)


def _matrix_final_pose(
    *,
    start_pose: Sequence[float],
    layer_heights_mm: Sequence[float],
    extrusion_scales: Sequence[float],
    line_length_mm: float,
    y_spacing_mm: float,
    finish_lift_mm: float,
    shift_y_after_each_line: bool = False,
) -> tuple[float, float, float, float, float, float]:
    x, y, z, a, b, c = _pose_values(start_pose)
    layer_heights = _validate_positive_sequence(layer_heights_mm, "层高")
    scales = _validate_positive_sequence(extrusion_scales, "挤出倍率")
    line_count = len(layer_heights) * len(scales)
    final_x = x + float(line_length_mm) if line_count % 2 == 1 else x
    if shift_y_after_each_line:
        final_y = y + line_count * float(y_spacing_mm)
    else:
        final_y = y + (line_count - 1) * float(y_spacing_mm)
    final_z = z + layer_heights[-1] + float(finish_lift_mm)
    return final_x, final_y, final_z, a, b, c


def _append_tool_change_compensation(
    lines: list[str],
    *,
    current_pose: Sequence[float],
    delta_xyz: Sequence[float],
    safe_lift_mm: float,
    speed_mm_s: float,
) -> tuple[float, float, float, float, float, float]:
    x, y, z, a, b, c = _pose_values(current_pose)
    if len(delta_xyz) != 3:
        raise ValueError("delta_xyz must contain X/Y/Z")
    dx, dy, dz = (float(v) for v in delta_xyz)
    safe_lift = float(safe_lift_mm)
    if safe_lift < 0.0:
        raise ValueError("safe_lift_mm must be >= 0")
    feed = _feed(speed_mm_s)
    lifted_z = z + safe_lift
    lines.append(f";TOOL_CHANGE_SAFE_LIFT:{safe_lift:.6f}")
    lines.append(
        f"G0 X{x:.6f} Y{y:.6f} Z{lifted_z:.6f} "
        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
    )
    target_pose = (x + dx, y + dy, lifted_z + dz, a, b, c)
    tx, ty, tz, ta, tb, tc = target_pose
    lines.append(f";TOOL_CHANGE_COMPENSATION:{dx:.6f},{dy:.6f},{dz:.6f}")
    lines.append(
        f"G0 X{tx:.6f} Y{ty:.6f} Z{tz:.6f} "
        f"A{ta:.6f} B{tb:.6f} C{tc:.6f} F{feed:.3f}"
    )
    return target_pose


def _matrix_body_without_header(lines: Sequence[str]) -> list[str]:
    return list(lines[len(_header((0.0, 0.0, 0.0, 0.0, 0.0, 0.0))):])


def generate_composite_test_matrix_gcode(
    *,
    start_pose: Sequence[float],
    resin_layer_heights_mm: Sequence[float],
    resin_extrusion_scales: Sequence[float],
    fiber_layer_heights_mm: Sequence[float],
    fiber_extrusion_scales: Sequence[float],
    speed_mm_s: float,
    line_length_mm: float = 300.0,
    y_spacing_mm: float = 10.0,
    finish_lift_mm: float = 10.0,
    max_lines: int = TEST_MATRIX_MAX_LINES,
    prime_length_mm: float = 0.0,
    retract_length_mm: float = 0.0,
    prime_speed_mm_s: float = 2.0,
    retract_speed_mm_s: float = 8.0,
    fiber_prime_length_mm: float = 0.0,
    fiber_retract_length_mm: float = 0.0,
    fiber_prime_speed_mm_s: float = 2.0,
    fiber_retract_speed_mm_s: float = 8.0,
    calibration: HeadCalibration | None = None,
    tool_change_safe_lift_mm: float = 10.0,
) -> list[str]:
    active_calibration = calibration if calibration is not None else HeadCalibration()
    tool_change_safe_lift = float(tool_change_safe_lift_mm)
    if tool_change_safe_lift < 0.0:
        raise ValueError("tool_change_safe_lift_mm must be >= 0")

    resin_layer_heights = _validate_positive_sequence(resin_layer_heights_mm, "层高")
    fiber_layer_heights = _validate_positive_sequence(fiber_layer_heights_mm, "层高")
    x, y, z, a, b, c = _pose_values(start_pose)
    feed = _feed(speed_mm_s)
    lines = _header(start_pose, reset_e=False)

    start_safe_z = z + tool_change_safe_lift
    lines.append(f";TOOL_CHANGE_SAFE_LIFT:{tool_change_safe_lift:.6f}")
    lines.append(
        f"G0 X{x:.6f} Y{y:.6f} Z{start_safe_z:.6f} "
        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
    )
    lines.append(f"T{RESIN_GCODE_TOOL}")
    lines.append("G92 E0")

    # Composite starts from the confirmed fiber pose, which already includes
    # the global resin Z print compensation. Tool-change deltas here use only
    # the measured fiber-head offset so the global Z is neither dropped nor doubled.
    fr_dx = -float(active_calibration.fiber_x_print_compensation_mm)
    fr_dy = -float(active_calibration.fiber_y_print_compensation_mm)
    fr_dz = -float(active_calibration.fiber_z_print_compensation_mm)
    resin_start_pose = (x + fr_dx, y + fr_dy, z + fr_dz, a, b, c)
    lines.append(f";TOOL_CHANGE_COMPENSATION:{fr_dx:.6f},{fr_dy:.6f},{fr_dz:.6f}")
    lines.append(
        f"G0 X{x + fr_dx:.6f} Y{y + fr_dy:.6f} Z{start_safe_z + fr_dz:.6f} "
        f"A{a:.6f} B{b:.6f} C{c:.6f} F{feed:.3f}"
    )

    resin_lines = generate_test_matrix_gcode(
        start_pose=resin_start_pose,
        layer_heights_mm=resin_layer_heights,
        extrusion_scales=resin_extrusion_scales,
        speed_mm_s=speed_mm_s,
        line_length_mm=line_length_mm,
        y_spacing_mm=y_spacing_mm,
        finish_lift_mm=finish_lift_mm,
        max_lines=max_lines,
        prime_length_mm=prime_length_mm,
        retract_length_mm=retract_length_mm,
        prime_speed_mm_s=prime_speed_mm_s,
        retract_speed_mm_s=retract_speed_mm_s,
        lift_between_lines=False,
    )
    lines.extend(_matrix_body_without_header(resin_lines))

    resin_final_pose = _matrix_final_pose(
        start_pose=resin_start_pose,
        layer_heights_mm=resin_layer_heights,
        extrusion_scales=resin_extrusion_scales,
        line_length_mm=line_length_mm,
        y_spacing_mm=y_spacing_mm,
        finish_lift_mm=finish_lift_mm,
        shift_y_after_each_line=True,
    )
    resin_start_x, resin_start_y, resin_start_z, resin_a, resin_b, resin_c = (
        _pose_values(resin_start_pose)
    )
    _final_x, _final_y, final_safe_z, _final_a, _final_b, _final_c = resin_final_pose
    lines.append(";RETURN_TO_RESIN_START")
    lines.append(
        f"G0 X{resin_start_x:.6f} Y{resin_start_y:.6f} Z{final_safe_z:.6f} "
        f"A{resin_a:.6f} B{resin_b:.6f} C{resin_c:.6f} F{feed:.3f}"
    )
    lines.append(f"T{FIBER_GCODE_TOOL}")
    lines.append("G92 E0")

    rf_dx = float(active_calibration.fiber_x_print_compensation_mm)
    rf_dy = float(active_calibration.fiber_y_print_compensation_mm)
    rf_dz = float(active_calibration.fiber_z_print_compensation_mm)
    fiber_safe_x = resin_start_x + rf_dx
    fiber_safe_y = resin_start_y + rf_dy
    # Composite fiber is laid on top of the first resin line surface.
    fiber_base_z = resin_start_z + resin_layer_heights[0] + rf_dz
    fiber_start_pose = (
        fiber_safe_x,
        fiber_safe_y,
        fiber_base_z,
        resin_a,
        resin_b,
        resin_c,
    )
    fiber_safe_z = final_safe_z + rf_dz
    lines.append(f";TOOL_CHANGE_COMPENSATION:{rf_dx:.6f},{rf_dy:.6f},{rf_dz:.6f}")
    lines.append(
        f"G0 X{fiber_safe_x:.6f} Y{fiber_safe_y:.6f} Z{fiber_safe_z:.6f} "
        f"A{resin_a:.6f} B{resin_b:.6f} C{resin_c:.6f} F{feed:.3f}"
    )

    # Composite test GCode bakes in head compensation; export with
    # tool_offset=(0, 0, 0) to avoid applying the offset twice.
    fiber_lines = generate_test_matrix_gcode(
        start_pose=fiber_start_pose,
        layer_heights_mm=fiber_layer_heights,
        extrusion_scales=fiber_extrusion_scales,
        speed_mm_s=speed_mm_s,
        line_length_mm=line_length_mm,
        y_spacing_mm=y_spacing_mm,
        finish_lift_mm=finish_lift_mm,
        max_lines=max_lines,
        prime_length_mm=fiber_prime_length_mm,
        retract_length_mm=fiber_retract_length_mm,
        prime_speed_mm_s=fiber_prime_speed_mm_s,
        retract_speed_mm_s=fiber_retract_speed_mm_s,
        extrude_by_path_length=True,
    )
    lines.extend(_matrix_body_without_header(fiber_lines))
    return lines


def format_gcode(lines: Iterable[str]) -> str:
    return "\n".join(lines) + "\n"
